[2024-06-06T03:18:53.291+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:18:53.773+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-06-06T03:18:53.956+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-06-06T03:18:53.957+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:18:54.084+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-01-03 00:00:00+00:00
[2024-06-06T03:18:54.359+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpivppqfgh']
[2024-06-06T03:18:54.410+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask test_first_connection
[2024-06-06T03:18:54.492+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=262) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:18:54.499+0000] {standard_task_runner.py:63} INFO - Started process 296 to run task
[2024-06-06T03:18:54.968+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:18:55.730+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-06-06T03:18:55.746+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:18:55.941+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:18:55.950+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: <lambda>() missing 1 required positional argument: '_'
[2024-06-06T03:18:56.018+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-01-03T00:00:00+00:00, execution_date=20230103T000000, start_date=20240606T031853, end_date=20240606T031856
[2024-06-06T03:18:56.192+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task test_first_connection (<lambda>() missing 1 required positional argument: '_'; 296)
[2024-06-06T03:18:56.286+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T03:18:56.331+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-06T03:33:13.879+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:33:14.099+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-06-06T03:33:14.407+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-06-06T03:33:14.425+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:33:14.597+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-01-03 00:00:00+00:00
[2024-06-06T03:33:14.838+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1140) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:33:14.844+0000] {standard_task_runner.py:63} INFO - Started process 1184 to run task
[2024-06-06T03:33:14.871+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpcz0z22f0']
[2024-06-06T03:33:14.890+0000] {standard_task_runner.py:91} INFO - Job 204: Subtask test_first_connection
[2024-06-06T03:33:15.337+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:33:15.986+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-06-06T03:33:16.002+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:33:16.227+0000] {logging_mixin.py:188} INFO - testing task1
[2024-06-06T03:33:16.241+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-06T03:33:16.261+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:33:16.350+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-01-03T00:00:00+00:00, execution_date=20230103T000000, start_date=20240606T033314, end_date=20240606T033316
[2024-06-06T03:33:17.103+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T03:33:17.256+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T03:33:17.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-06T03:45:40.709+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:45:41.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-06-06T03:45:41.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2024-06-06T03:45:41.244+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:45:41.474+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-01-03 00:00:00+00:00
[2024-06-06T03:45:41.518+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1566) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:45:41.526+0000] {standard_task_runner.py:63} INFO - Started process 1607 to run task
[2024-06-06T03:45:41.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmp45z79b5p']
[2024-06-06T03:45:41.580+0000] {standard_task_runner.py:91} INFO - Job 248: Subtask test_first_connection
[2024-06-06T03:45:41.869+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-01-03T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:45:42.682+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-03T00:00:00+00:00'
[2024-06-06T03:45:42.690+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:45:42.811+0000] {logging_mixin.py:188} INFO - testing task1
[2024-06-06T03:45:42.832+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-06T03:45:42.839+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:45:42.886+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-01-03T00:00:00+00:00, execution_date=20230103T000000, start_date=20240606T034541, end_date=20240606T034542
[2024-06-06T03:45:43.041+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-06T03:45:43.082+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
