[2024-06-07T10:46:28.621+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T10:46:28.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-07T10:46:25.861541+00:00 [queued]>
[2024-06-07T10:46:28.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-07T10:46:25.861541+00:00 [queued]>
[2024-06-07T10:46:28.676+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-07T10:46:28.712+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_nextDay1> on 2024-06-07 10:46:25.861541+00:00
[2024-06-07T10:46:28.725+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_nextDay1', 'manual__2024-06-07T10:46:25.861541+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmp6yjtg544']
[2024-06-07T10:46:28.728+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask upload_nextDay1
[2024-06-07T10:46:28.731+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4424) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-07T10:46:28.738+0000] {standard_task_runner.py:63} INFO - Started process 4431 to run task
[2024-06-07T10:46:28.822+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-07T10:46:25.861541+00:00 [running]> on host 6c00989aad97
[2024-06-07T10:46:29.061+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_nextDay1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-07T10:46:25.861541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-07T10:46:25.861541+00:00'
[2024-06-07T10:46:29.063+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T10:46:29.092+0000] {logging_mixin.py:188} INFO - creating nextDayFolder...
[2024-06-07T10:46:29.111+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-07T10:46:29.112+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-07T10:46:29.726+0000] {logging_mixin.py:188} INFO - prefix for next day already exist
[2024-06-07T10:46:29.727+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-07T10:46:29.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T10:46:29.743+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_nextDay1, run_id=manual__2024-06-07T10:46:25.861541+00:00, execution_date=20240607T104625, start_date=20240607T104628, end_date=20240607T104629
[2024-06-07T10:46:29.789+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-07T10:46:29.809+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T10:46:29.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
