[2024-06-06T03:20:58.049+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:20:58.145+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-02-15T00:00:00+00:00 [queued]>
[2024-06-06T03:20:58.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-02-15T00:00:00+00:00 [queued]>
[2024-06-06T03:20:58.254+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:20:58.656+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-02-15 00:00:00+00:00
[2024-06-06T03:20:58.731+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=567) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:20:58.720+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-02-15T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpdkzzez6m']
[2024-06-06T03:20:58.739+0000] {standard_task_runner.py:91} INFO - Job 104: Subtask test_first_connection
[2024-06-06T03:20:58.733+0000] {standard_task_runner.py:63} INFO - Started process 584 to run task
[2024-06-06T03:20:58.988+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-02-15T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:20:59.414+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-02-15T00:00:00+00:00'
[2024-06-06T03:20:59.439+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:20:59.480+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:20:59.487+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: <lambda>() missing 1 required positional argument: '_'
[2024-06-06T03:20:59.534+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-02-15T00:00:00+00:00, execution_date=20230215T000000, start_date=20240606T032058, end_date=20240606T032059
[2024-06-06T03:20:59.562+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 104 for task test_first_connection (<lambda>() missing 1 required positional argument: '_'; 584)
[2024-06-06T03:20:59.616+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T03:20:59.636+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-06-06T03:20:59.668+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T03:20:59.684+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
