[2024-06-08T08:25:50.418+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-08T08:25:50.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:25:50.511+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [queued]>
[2024-06-08T08:25:50.512+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2024-06-08T08:25:50.593+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_nextDay1> on 2024-06-08 07:11:19.232646+00:00
[2024-06-08T08:25:50.636+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_t1', 'upload_nextDay1', 'manual__2024-06-08T07:11:19.232646+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/Etl_Dag.py', '--cfg-path', '/tmp/tmpizp516xe']
[2024-06-08T08:25:50.634+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3163) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-08T08:25:50.643+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask upload_nextDay1
[2024-06-08T08:25:50.660+0000] {standard_task_runner.py:63} INFO - Started process 3184 to run task
[2024-06-08T08:25:50.937+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_t1.upload_nextDay1 manual__2024-06-08T07:11:19.232646+00:00 [running]> on host 6c00989aad97
[2024-06-08T08:25:51.408+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_t1' AIRFLOW_CTX_TASK_ID='upload_nextDay1' AIRFLOW_CTX_EXECUTION_DATE='2024-06-08T07:11:19.232646+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-08T07:11:19.232646+00:00'
[2024-06-08T08:25:51.409+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-08T08:25:51.462+0000] {logging_mixin.py:188} INFO - creating nextDayFolder...
[2024-06-08T08:25:51.490+0000] {base.py:84} INFO - Using connection ID 's3_conn' for task execution.
[2024-06-08T08:25:51.492+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from extra.
[2024-06-08T08:25:52.981+0000] {logging_mixin.py:188} INFO - landing prefix for next day already exist
[2024-06-08T08:25:52.992+0000] {logging_mixin.py:188} INFO - transfrom prefix for next day already exist
[2024-06-08T08:25:52.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-08T08:25:52.999+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-08T08:25:53.025+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_t1, task_id=upload_nextDay1, run_id=manual__2024-06-08T07:11:19.232646+00:00, execution_date=20240608T071119, start_date=20240608T082550, end_date=20240608T082553
[2024-06-08T08:25:53.138+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-08T08:25:53.182+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-08T08:25:53.185+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
