[2024-06-06T03:22:12.820+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-06T03:22:12.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-03-12T00:00:00+00:00 [queued]>
[2024-06-06T03:22:13.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-03-12T00:00:00+00:00 [queued]>
[2024-06-06T03:22:13.020+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-06T03:22:13.161+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_first_connection> on 2023-03-12 00:00:00+00:00
[2024-06-06T03:22:13.239+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=739) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-06T03:22:13.226+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_testConnection_v1', 'test_first_connection', 'scheduled__2023-03-12T00:00:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/TestConnectionDag.py', '--cfg-path', '/tmp/tmpeq3wiyo6']
[2024-06-06T03:22:13.256+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask test_first_connection
[2024-06-06T03:22:13.257+0000] {standard_task_runner.py:63} INFO - Started process 781 to run task
[2024-06-06T03:22:13.476+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_testConnection_v1.test_first_connection scheduled__2023-03-12T00:00:00+00:00 [running]> on host fe4af7f6193a
[2024-06-06T03:22:14.854+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_testConnection_v1' AIRFLOW_CTX_TASK_ID='test_first_connection' AIRFLOW_CTX_EXECUTION_DATE='2023-03-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-12T00:00:00+00:00'
[2024-06-06T03:22:14.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-06T03:22:15.340+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-06T03:22:15.358+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: <lambda>() missing 1 required positional argument: '_'
[2024-06-06T03:22:15.623+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_testConnection_v1, task_id=test_first_connection, run_id=scheduled__2023-03-12T00:00:00+00:00, execution_date=20230312T000000, start_date=20240606T032212, end_date=20240606T032215
[2024-06-06T03:22:15.819+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task test_first_connection (<lambda>() missing 1 required positional argument: '_'; 781)
[2024-06-06T03:22:16.021+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-06T03:22:16.191+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class MySqlOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-06-06T03:22:16.290+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-06T03:22:16.357+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
